#!/usr/bin/env python

import os, optparse
import numpy as np

import xraylib
from xraylib import f2w, files, utils

class Averager(utils.Script):
    def __init__(self):
        super(Averager, self).__init__()
        description = """
        Merge diffraction images and write average to file.
        """
    def parser_setup(self):
        super(Averager, self).parser_setup()

        output_group = optparse.OptionGroup(self.parser, "Output options")
        output_group.add_option("-o", "--out", dest="outfile",
                          help="File to save averaged dataset", metavar="FILE", default="averaged.h5")
        output_group.add_option("--data-set", dest="data_set",
                          help="Location to save data set (hdf5 etc).", metavar="STRING", default=xraylib.AVERAGE_DATA_SET)
        self.parser.add_option_group(output_group)
        self.parser.add_option("--method",
                          dest="method", default="median",
                          metavar="[median][mean]", help="Choose between arithmetic mean and median.")
        self.parser.add_option("--flatten", dest="flatten",
                          action="store_true", default=False,
                          help="Average over frames in multiframe files.")

    def parse(self):
        super(Averager, self).parse()

        if len(self.args) == 0:
            self.parser.error("Please provide some images to average.")

        if len(self.options.data_set.split('/')) < 2:
            self.parser.error("Dataset should be on the form '/group_name/data_set'.")

    @utils.Script.timed
    def average(self):
        self.image = files.averageImages(self.args,method=self.options.method, flatten=self.options.flatten)

    @utils.Script.timed
    def output(self):
        out = files.ImageFile(self.options.outfile)
        out.saveImage(self.image, self.options.data_set)


if __name__ == '__main__':
    avg = Averager()

    avg.parser_setup()
    avg.parse()
    avg.average()
    avg.output()
    avg.print_timings()

