#!/usr/bin/env python

import numpy as np
import os, optparse
import h5py, fabio

from skimage import transform

import xraylib
from xraylib import files, utils, tomo

class Reconstructor(utils.Script):
    def __init__(self, **kwargs):
        super(Reconstructor, self).__init__()
        self.description = """
        Correct sinograms and perform reconstruction.
        By default the sinogram is split into odd and even rows
        which are correlated to correct for offset in interleaved
        scans, followed by a search for the center of rotation.
        """

    def parser_setup(self):
        super(Reconstructor, self).parser_setup()

        input_group = optparse.OptionGroup(self.parser, "Input options")
        input_group.add_option("--sinogram-group", dest="sinogram_group",
                          help="", default=None)
        input_group.add_option("--iterations", dest="sart_iterations", default=1,
                          help="Number of iterations to perform SART reconstruction. [default=1]")
        self.parser.add_option("--correct_center", dest="correct_center",
                          action="store_true", default=True,
                          help="Attempt to find center of rotation.")
        self.parser.add_option("--correct_interlacing", dest="correct_center",
                          action="store_true", default=True,
                          help="Perform deinterlacing.")


        output_group = optparse.OptionGroup(self.parser, "Output options")
        output_group.add_option("--output-sinogram", dest="output_sinogram",
                          action="store_true", default=True)
        output_group.add_option("--output-reconstruction", dest="output_reconstruction",
                          action="store_true", default=True)

        self.parser.add_option_group(input_group)
        self.parser.add_option_group(output_group)

    @utils.Script.timed
    def parse(self):
        super(Reconstructor, self).parse()

        self.sart_iterations = utils.convert(self.options.sart_iterations,int)

        if len(self.args) > 1 or len(self.args) == 0:
            self.parser.error("Please specify one and only one sinogram file")

        try:
            self.sino_file = h5py.File(self.args[0])
        except:
            self.parser.error("Could not open sinogram")

        if not xraylib.SINOGRAM_GROUP in self.sino_file:
            self.parser.error('File does not have group %s' % (xraylib.SINOGRAM_GROUP,))

        self.sino_group = self.sino_file[xraylib.SINOGRAM_GROUP]

        self.corrected_group = self.sino_file.require_group(xraylib.CORRECTED_SINOGRAM_GROUP)
        self.reconstruction_group = self.sino_file.require_group(xraylib.RECONSTRUCTION_GROUP)


    @utils.Script.timed
    def process_sinograms(self):
        for key,data_set in self.sino_group.items():
            self.print_verbose("--->  ", key)
            sinogram = data_set.value
            if len(data_set.shape) > 2:
                slices = data_set.shape[0]
            else:
                slices = 1
                sinogram.shape = (1,)+data_set.shape

            corrected_dataset = self.corrected_group.require_dataset(
                    name=key,
                    shape=sinogram.squeeze().shape,
                    dtype="float32"
            )
            ret = np.zeros(sinogram.shape)
            for i in xrange(0,slices):
                corrected_sinogram = tomo.sino_deinterlace(sinogram[i])
                corrected_sinogram = tomo.sino_center(corrected_sinogram)
                corrected_sinogram = tomo.sino_remove_bragg_spots(corrected_sinogram)

                ret[i,...] = corrected_sinogram

            corrected_dataset[:] = ret.squeeze()


    @utils.Script.timed
    def reconstruct(self):
        for key,data_set in self.corrected_group.items():
            corrected_sinogram = data_set.value
            if len(data_set.shape) > 2:
                slices = data_set.shape[0]
            else:
                slices = 1
                corrected_sinogram.shape= (1,)+data_set.shape

            for i in xrange(0,slices):
                # skimage expects columns of projections so transpose
                sino = corrected_sinogram[i].astype('double').T

                if key in self.reconstruction_group:
                    del self.reconstruction_group[key]
                reconstruction_dataset = self.reconstruction_group.require_dataset(
                        name=key,
                        shape=(slices,)+tuple([sino.shape[0]]*2),
                        dtype="float32"
                )

                # Do a fast, filtered back projection reconstruction
                # as initial guess for the SART reconstruction procedure
                reconstruction = transform.iradon(
                        sino,
                        output_size = sino.shape[0]
                )
                try:
                    for it in xrange(0,self.sart_iterations):
                        reconstruction = transform.iradon_sart(
                                sino,
                                image=reconstruction
                        )
                except AttributeError:
                    self.print_verbose("This version of skimage does not support SART reconstruction")

                reconstruction_dataset[i] = reconstruction

    @utils.Script.timed
    def output(self):
        self.sino_file.close()

if __name__ == '__main__':
    reconst = Reconstructor()

    reconst.parser_setup()
    reconst.parse()
    reconst.process_sinograms()
    reconst.reconstruct()
    reconst.output()
else:
    pass
    # Initialize assmbl with values from DAWN
    # assmbl = Reconstructor(position=.., fwhm = ..., shape="gaussian")
